<?php

return [
    [
        'title' => 'test title 1',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => 199,
        'new' => true,
        'img'  => '/img/bag.png',
    ],
    [
        'title' => 'test title 2',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/child_jacket.png',
    ],
    [
        'title' => 'test title 3',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 125,
        'new' => true,
        'discountCost' => null,
        'img'  => '/img/jeans_pants.png',
    ],
    [
        'title' => 'test title 4',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 111,
        'discountCost' => 90,
        'new' => false,
        'img'  => '/img/man_coat.png',
    ],
    [
        'title' => 'test title 5',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => true,
        'img'  => '/img/man_sweater.png',
    ],
    [
        'title' => 'test title 6',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => true,
        'img'  => '/img/sport_dress.png',
    ],
    [
        'title' => 'test title 7',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/woman_coat.png',
    ],
    [
        'title' => 'test title 8',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/woman_short.png',
    ],
    [
        'title' => 'test title 9',
        'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
        'cost' => 249,
        'discountCost' => null,
        'new' => false,
        'img'  => '/img/sport_dress.png',
    ],
     [
            'title' => 'test title 10',
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
            'cost' => 249,
            'discountCost' => 199,
            'new' => true,
            'img'  => '/img/bag.png',
        ],
        [
            'title' => 'test title 11',
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
            'cost' => 249,
            'discountCost' => null,
            'new' => false,
            'img'  => '/img/child_jacket.png',
        ],
        [
            'title' => 'test title 12',
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
            'cost' => 125,
            'new' => true,
            'discountCost' => null,
            'img'  => '/img/jeans_pants.png',
        ],
        [
            'title' => 'test title 13',
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
            'cost' => 111,
            'discountCost' => 90,
            'new' => false,
            'img'  => '/img/man_coat.png',
        ],
        [
            'title' => 'test title 14',
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
            'cost' => 249,
            'discountCost' => null,
            'new' => true,
            'img'  => '/img/man_sweater.png',
        ],
        [
            'title' => 'test title 15',
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
            'cost' => 249,
            'discountCost' => null,
            'new' => true,
            'img'  => '/img/sport_dress.png',
        ],
        [
            'title' => 'test title 16',
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
            'cost' => 249,
            'discountCost' => null,
            'new' => false,
            'img'  => '/img/woman_coat.png',
        ],
        [
            'title' => 'test title 17',
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
            'cost' => 249,
            'discountCost' => null,
            'new' => false,
            'img'  => '/img/woman_short.png',
        ],
        [
            'title' => 'test title 18',
            'description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ',
            'cost' => 249,
            'discountCost' => null,
            'new' => false,
            'img'  => '/img/sport_dress.png',
        ],
];